customhost = "ccassignment.clwe6mkxcp4t.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "ccAssignment"
custombucket = "ccassignment-bucket"     
customregion = "us-east-1"
